// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLoggerAPI.Ledana.Data;

#nullable disable

namespace ShiftsLoggerAPI.Ledana.Migrations
{
    [DbContext(typeof(ShiftContext))]
    partial class ShiftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftsLoggerAPI.Ledana.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Amelia",
                            LastName = "Aster"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Lory",
                            LastName = "Marti"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Laila",
                            LastName = "Martini"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Vivian",
                            LastName = "Scott"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Luiza",
                            LastName = "Griffin"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Violet",
                            LastName = "Jinx"
                        });
                });

            modelBuilder.Entity("ShiftsLoggerAPI.Ledana.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT(varchar(5), DATEADD(MINUTE, DATEDIFF(minute, [StartTime], [EndTime]), 0),108)", true);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 5, 1, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 1, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 3,
                            EndTime = new DateTime(2026, 5, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 4,
                            EndTime = new DateTime(2026, 5, 1, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 5,
                            EndTime = new DateTime(2026, 5, 1, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 1, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 6, 2, 5, 35, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 1, 23, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 3,
                            EndTime = new DateTime(2026, 5, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 2, 6, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 4,
                            EndTime = new DateTime(2026, 5, 2, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 5,
                            EndTime = new DateTime(2026, 5, 2, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 2, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 6,
                            EndTime = new DateTime(2026, 6, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 2, 22, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 1,
                            EndTime = new DateTime(2026, 5, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 3, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 5, 3, 23, 55, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 3, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 5,
                            EndTime = new DateTime(2026, 5, 4, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 4, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 5, 6, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 6, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 3,
                            EndTime = new DateTime(2026, 5, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 6, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 4,
                            EndTime = new DateTime(2026, 5, 7, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 5,
                            EndTime = new DateTime(2026, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 8, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 6, 9, 5, 35, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 8, 23, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 3,
                            EndTime = new DateTime(2026, 5, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 8, 6, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 4,
                            EndTime = new DateTime(2026, 5, 9, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 3,
                            EndTime = new DateTime(2026, 5, 9, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 9, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 6,
                            EndTime = new DateTime(2026, 6, 10, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 9, 22, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 1,
                            EndTime = new DateTime(2026, 5, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 9, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 2,
                            EndTime = new DateTime(2026, 5, 9, 23, 25, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 9, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 5,
                            EndTime = new DateTime(2026, 5, 10, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 5, 9, 21, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ShiftsLoggerAPI.Ledana.Models.Shift", b =>
                {
                    b.HasOne("ShiftsLoggerAPI.Ledana.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ShiftsLoggerAPI.Ledana.Models.Employee", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
